spring.application.name=mvs


#app.datasource.reg.url=jdbc:postgresql://192.168.1.232:5432/voter_reg
app.datasource.reg.url=jdbc:postgresql://192.168.1.25:5432/voter_reg
app.datasource.reg.username=postgres
#app.datasource.reg.password=Eagle@213
app.datasource.reg.password=Msp@321#

#server.servlet.context-path=/mvs

#app.datasource.afis.url=jdbc:postgresql://192.168.1.232:5432/voter_afis_dedupe
app.datasource.afis.url=jdbc:postgresql://192.168.1.25:5432/voter_afis_dedupe
app.datasource.afis.username=postgres
#app.datasource.afis.password=Eagle@213
app.datasource.afis.password=Msp@321#

app.datasource.mvs.url=jdbc:postgresql://192.168.1.232:5432/mvs
#app.datasource.afis.url=jdbc:postgresql://localhost:5432/voter_afis_dedupe
app.datasource.mvs.username=postgres
#app.datasource.afis.password=Eagle@213
app.datasource.mvs.password=Msp@321#

spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081